name: Deploy Frontend

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  s3:
    name: "Push to S3"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::362124138558:role/github-eks-deployer"
          aws-region: us-east-1
          mask-aws-account-id: "no"
      - name: Upload to S3
        run: |
          aws s3 cp frontend/websocket.html s3://war-frontend/websocket.html
